from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, Dict, Iterable, List, Optional, Protocol, runtime_checkable


@runtime_checkable
class IPipeline(Protocol):
    """Интерфейс для всех реализаций pipeline.

    Основан на уже существующем `PipelineBase`, но не навязывает наследование.
    Используется как контракт между контроллером, API и реализациями pipeline.
    """

    # Жизненный цикл
    def init(self, **kwargs: Any) -> bool: ...

    def start(self) -> None: ...

    def stop(self) -> None: ...

    def reset(self) -> None: ...

    # Конфигурация
    def set_params(self, **params: Any) -> None: ...

    def get_params(self) -> Dict[str, Any]: ...

    def set_credentials(self, credentials: Dict[str, Any]) -> None: ...

    def get_credentials(self) -> Optional[Dict[str, Any]]: ...

    # Основная обработка
    def process(self) -> Dict[str, Any]: ...

    # Доступ к источникам и результатам
    def get_sources(self) -> List[Any]: ...

    def get_results_list(self) -> List[Dict[str, Any]]: ...

    def get_current_results(self) -> Dict[str, Any]: ...


@runtime_checkable
class IObjectHandler(Protocol):
    """Интерфейс обработчика объектов.

    Основан на `ObjectsHandler`, но не требует прямого наследования.
    """

    # Жизненный цикл
    def init(self, **kwargs: Any) -> bool: ...

    def start(self) -> None: ...

    def stop(self) -> None: ...

    def reset(self) -> None: ...

    # Конфигурация
    def set_params(self, **params: Any) -> None: ...

    def get_params(self) -> Dict[str, Any]: ...

    # Основное API
    def put(self, data: Dict[str, Any]) -> None: ...

    def get(self, objs_type: str, cam_id: int) -> Any: ...

    def subscribe(self, *subscribers: Any) -> None: ...


@runtime_checkable
class IEventDetector(Protocol):
    """Интерфейс детектора событий (одного типа)."""

    # Жизненный цикл
    def init(self, **kwargs: Any) -> bool: ...

    def start(self) -> None: ...

    def stop(self) -> None: ...

    def reset(self) -> None: ...

    # Основное API
    def put(self, data: Any) -> None: ...

    def get(self) -> Iterable[Any]: ...

    def get_name(self) -> str: ...


@runtime_checkable
class IDatabaseAdapter(Protocol):
    """Интерфейс адаптера БД / JSON хранилища."""

    # Жизненный цикл
    def init(self, **kwargs: Any) -> bool: ...

    def start(self) -> None: ...

    def stop(self) -> None: ...

    def reset(self) -> None: ...

    # Конфигурация
    def set_params(self, **params: Any) -> None: ...

    def get_params(self) -> Dict[str, Any]: ...

    # Операции записи
    def insert(self, data: Dict[str, Any]) -> None: ...

    def update(self, data: Dict[str, Any]) -> None: ...

    # Метаданные
    def get_table_name(self) -> Optional[str]: ...

    def get_event_name(self) -> Optional[str]: ...


@runtime_checkable
class IVisualizer(Protocol):
    """Интерфейс визуализатора."""

    # Жизненный цикл
    def init(self, **kwargs: Any) -> bool: ...

    def start(self) -> None: ...

    def stop(self) -> None: ...

    def reset(self) -> None: ...

    # Конфигурация
    def set_params(self, **params: Any) -> None: ...

    def get_params(self) -> Dict[str, Any]: ...

    # Основное API
    def update(
        self,
        processing_frames: List[Any],
        source_last_processed_frame_id: Dict[int, int],
        objects: List[Any],
        dropped_frames: List[Any],
        debug_info: Dict[str, Any],
    ) -> None: ...

    def set_signal_params(self, enabled: bool, color_rgb: tuple[int, int, int]) -> None: ...

